#This auto-generated singleton preloads small nodes such as equipment and can instantiate them as needed
extends Node

#Equipment section
const equipmentSceneDictionary = {
#Weapon
	"adamantium_greataxe" : preload("res://ScenePreloads/Equipment_new/Weapon/adamantium_greataxe.tscn"),
	"arming_sword" : preload("res://ScenePreloads/Equipment_new/Weapon/arming_sword.tscn"),
	"bardiche" : preload("res://ScenePreloads/Equipment_new/Weapon/bardiche.tscn"),
	"blade_of_darkness" : preload("res://ScenePreloads/Equipment_new/Weapon/blade_of_darkness.tscn"),
	"blade_of_sin" : preload("res://ScenePreloads/Equipment_new/Weapon/blade_of_sin.tscn"),
	"blunderbuss" : preload("res://ScenePreloads/Equipment_new/Weapon/blunderbuss.tscn"),
	"club" : preload("res://ScenePreloads/Equipment_new/Weapon/club.tscn"),
	"crackling_greataxe" : preload("res://ScenePreloads/Equipment_new/Weapon/crackling_greataxe.tscn"),
	"crossbow" : preload("res://ScenePreloads/Equipment_new/Weapon/crossbow.tscn"),
	"crystal_sword" : preload("res://ScenePreloads/Equipment_new/Weapon/crystal_sword.tscn"),
	"cutlass" : preload("res://ScenePreloads/Equipment_new/Weapon/cutlass.tscn"),
	"dagger" : preload("res://ScenePreloads/Equipment_new/Weapon/dagger.tscn"),
	"deaths_scythe" : preload("res://ScenePreloads/Equipment_new/Weapon/deaths_scythe.tscn"),
	"diamond_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/diamond_staff.tscn"),
	"divine_greathammer" : preload("res://ScenePreloads/Equipment_new/Weapon/divine_greathammer.tscn"),
	"earth_hammer" : preload("res://ScenePreloads/Equipment_new/Weapon/earth_hammer.tscn"),
	"earth_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/earth_staff.tscn"),
	"emerald_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/emerald_staff.tscn"),
	"estoc" : preload("res://ScenePreloads/Equipment_new/Weapon/estoc.tscn"),
	"fire_spitter" : preload("res://ScenePreloads/Equipment_new/Weapon/fire_spitter.tscn"),
	"fire_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/fire_staff.tscn"),
	"flail" : preload("res://ScenePreloads/Equipment_new/Weapon/flail.tscn"),
	"flamberge" : preload("res://ScenePreloads/Equipment_new/Weapon/flamberge.tscn"),
	"force_wand" : preload("res://ScenePreloads/Equipment_new/Weapon/force_wand.tscn"),
	"frostfire_twindaggers" : preload("res://ScenePreloads/Equipment_new/Weapon/frostfire_twindaggers.tscn"),
	"greataxe" : preload("res://ScenePreloads/Equipment_new/Weapon/greataxe.tscn"),
	"greatsword" : preload("res://ScenePreloads/Equipment_new/Weapon/greatsword.tscn"),
	"great_flail" : preload("res://ScenePreloads/Equipment_new/Weapon/great_flail.tscn"),
	"halberd" : preload("res://ScenePreloads/Equipment_new/Weapon/halberd.tscn"),
	"hammer" : preload("res://ScenePreloads/Equipment_new/Weapon/hammer.tscn"),
	"handaxe" : preload("res://ScenePreloads/Equipment_new/Weapon/handaxe.tscn"),
	"hungering_blade" : preload("res://ScenePreloads/Equipment_new/Weapon/hungering_blade.tscn"),
	"ice_lance" : preload("res://ScenePreloads/Equipment_new/Weapon/ice_lance.tscn"),
	"ice_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/ice_staff.tscn"),
	"ice_sword" : preload("res://ScenePreloads/Equipment_new/Weapon/ice_sword.tscn"),
	"katana" : preload("res://ScenePreloads/Equipment_new/Weapon/katana.tscn"),
	"khopesh" : preload("res://ScenePreloads/Equipment_new/Weapon/khopesh.tscn"),
	"kunai" : preload("res://ScenePreloads/Equipment_new/Weapon/kunai.tscn"),
	"lance" : preload("res://ScenePreloads/Equipment_new/Weapon/lance.tscn"),
	"lightning_rod" : preload("res://ScenePreloads/Equipment_new/Weapon/lightning_rod.tscn"),
	"longbow" : preload("res://ScenePreloads/Equipment_new/Weapon/longbow.tscn"),
	"longsword" : preload("res://ScenePreloads/Equipment_new/Weapon/longsword.tscn"),
	"long_axe" : preload("res://ScenePreloads/Equipment_new/Weapon/long_axe.tscn"),
	"mace" : preload("res://ScenePreloads/Equipment_new/Weapon/mace.tscn"),
	"magma_greatsword" : preload("res://ScenePreloads/Equipment_new/Weapon/magma_greatsword.tscn"),
	"masamune" : preload("res://ScenePreloads/Equipment_new/Weapon/masamune.tscn"),
	"morning_star" : preload("res://ScenePreloads/Equipment_new/Weapon/morning_star.tscn"),
	"occult_wand" : preload("res://ScenePreloads/Equipment_new/Weapon/occult_wand.tscn"),
	"pike" : preload("res://ScenePreloads/Equipment_new/Weapon/pike.tscn"),
	"rapier" : preload("res://ScenePreloads/Equipment_new/Weapon/rapier.tscn"),
	"recurve_bow" : preload("res://ScenePreloads/Equipment_new/Weapon/recurve_bow.tscn"),
	"rhomphaia" : preload("res://ScenePreloads/Equipment_new/Weapon/rhomphaia.tscn"),
	"rondel_dagger" : preload("res://ScenePreloads/Equipment_new/Weapon/rondel_dagger.tscn"),
	"ruby_staff_new" : preload("res://ScenePreloads/Equipment_new/Weapon/ruby_staff_new.tscn"),
	"sapphire_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/sapphire_staff.tscn"),
	"scimitar" : preload("res://ScenePreloads/Equipment_new/Weapon/scimitar.tscn"),
	"scythe" : preload("res://ScenePreloads/Equipment_new/Weapon/scythe.tscn"),
	"shamshir" : preload("res://ScenePreloads/Equipment_new/Weapon/shamshir.tscn"),
	"shortbow" : preload("res://ScenePreloads/Equipment_new/Weapon/shortbow.tscn"),
	"shortsword" : preload("res://ScenePreloads/Equipment_new/Weapon/shortsword.tscn"),
	"shotel" : preload("res://ScenePreloads/Equipment_new/Weapon/shotel.tscn"),
	"sling_new" : preload("res://ScenePreloads/Equipment_new/Weapon/sling_new.tscn"),
	"spear" : preload("res://ScenePreloads/Equipment_new/Weapon/spear.tscn"),
	"staff_of_pain" : preload("res://ScenePreloads/Equipment_new/Weapon/staff_of_pain.tscn"),
	"star_rod" : preload("res://ScenePreloads/Equipment_new/Weapon/star_rod.tscn"),
	"throwing_axes" : preload("res://ScenePreloads/Equipment_new/Weapon/throwing_axes.tscn"),
	"topaz_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/topaz_staff.tscn"),
	"trident" : preload("res://ScenePreloads/Equipment_new/Weapon/trident.tscn"),
	"umbral_dagger" : preload("res://ScenePreloads/Equipment_new/Weapon/umbral_dagger.tscn"),
	"void_blade" : preload("res://ScenePreloads/Equipment_new/Weapon/void_blade.tscn"),
	"wand_of_disintigration" : preload("res://ScenePreloads/Equipment_new/Weapon/wand_of_disintigration.tscn"),
	"warbrand" : preload("res://ScenePreloads/Equipment_new/Weapon/warbrand.tscn"),
	"water_staff" : preload("res://ScenePreloads/Equipment_new/Weapon/water_staff.tscn"),
	"whip" : preload("res://ScenePreloads/Equipment_new/Weapon/whip.tscn"),
	"bat_bat" : preload("res://ScenePreloads/Equipment_old/Weapon/bat_bat.tscn"),
	"bat_staff" : preload("res://ScenePreloads/Equipment_old/Weapon/bat_staff.tscn"),
	"cat_claws" : preload("res://ScenePreloads/Equipment_old/Weapon/cat_claws.tscn"),
	"executioners_sword" : preload("res://ScenePreloads/Equipment_old/Weapon/executioners_sword.tscn"),
	"goose_flail" : preload("res://ScenePreloads/Equipment_old/Weapon/goose_flail.tscn"),
	"kiwi_dagger" : preload("res://ScenePreloads/Equipment_old/Weapon/kiwi_dagger.tscn"),
	"magic_stick_int" : preload("res://ScenePreloads/Equipment_old/Weapon/magic_stick_int.tscn"),
	"magic_stick_str" : preload("res://ScenePreloads/Equipment_old/Weapon/magic_stick_str.tscn"),
	"manticore_dart" : preload("res://ScenePreloads/Equipment_old/Weapon/manticore_dart.tscn"),
	"manticore_wand" : preload("res://ScenePreloads/Equipment_old/Weapon/manticore_wand.tscn"),
	"mole_pickaxe" : preload("res://ScenePreloads/Equipment_old/Weapon/mole_pickaxe.tscn"),
	"ram_spear" : preload("res://ScenePreloads/Equipment_old/Weapon/ram_spear.tscn"),
	"ruby_staff" : preload("res://ScenePreloads/Equipment_old/Weapon/ruby_staff.tscn"),
	"shiv" : preload("res://ScenePreloads/Equipment_old/Weapon/shiv.tscn"),
	"sling" : preload("res://ScenePreloads/Equipment_old/Weapon/sling.tscn"),
	"unarmed_Fighter" : preload("res://ScenePreloads/Equipment_old/Weapon/unarmed_Fighter.tscn"),
	"unarmed_Mage" : preload("res://ScenePreloads/Equipment_old/Weapon/unarmed_Mage.tscn"),
	"unarmed_Rogue" : preload("res://ScenePreloads/Equipment_old/Weapon/unarmed_Rogue.tscn"),
#Armor
	"casual" : preload("res://ScenePreloads/Equipment_old/Armor/casual.tscn"),
	"enchanted_robes" : preload("res://ScenePreloads/Equipment_old/Armor/enchanted_robes.tscn"),
	"feathered_cloak" : preload("res://ScenePreloads/Equipment_old/Armor/feathered_cloak.tscn"),
	"lion_armor" : preload("res://ScenePreloads/Equipment_old/Armor/lion_armor.tscn"),
	"manticore_armor" : preload("res://ScenePreloads/Equipment_old/Armor/manticore_armor.tscn"),
	"mole_armor" : preload("res://ScenePreloads/Equipment_old/Armor/mole_armor.tscn"),
	"scraps" : preload("res://ScenePreloads/Equipment_old/Armor/scraps.tscn"),
#Accessory
	"clown_horn" : preload("res://ScenePreloads/Equipment_old/Accessory/clown_horn.tscn"),
	"kiwi" : preload("res://ScenePreloads/Equipment_old/Accessory/kiwi.tscn"),
	"magpie_eye" : preload("res://ScenePreloads/Equipment_old/Accessory/magpie_eye.tscn"),
	"mandragora_potion" : preload("res://ScenePreloads/Equipment_old/Accessory/mandragora_potion.tscn"),
	"manticore_tooth" : preload("res://ScenePreloads/Equipment_old/Accessory/manticore_tooth.tscn"),
	"manticore_venom" : preload("res://ScenePreloads/Equipment_old/Accessory/manticore_venom.tscn"),
	"ram_horn" : preload("res://ScenePreloads/Equipment_old/Accessory/ram_horn.tscn"),
#Currency
	"pebble" : preload("res://ScenePreloads/Equipment_old/Currency/pebble.tscn")}

func createEquipmentScene(itemName : String) :
	var newScene = equipmentSceneDictionary[itemName].instantiate()
	newScene.core = EquipmentDatabase.getEquipment(itemName)
	return newScene
